### ISSUE TITLE
error: Could not compile `pear_codegen`.

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [ghotiphud/rust-web-starter#13]
The whole 'docker-compose up' log can be found here:
https://ghostbin.com/paste/ge55e

On localhost:3000 I can see a React logo spinning, including the following message:
"Proxy error: Could not proxy request /api from localhost:3000 to http://api_server:3001/ (ECONNREFUSED)."

I have tried running 'docker-compose build --no-cache api_server', but it still resulted in the same errors above.
Tried on both a Debian and Ubuntu computer, same results.

**Comment by ghotiphud** [comment]
This looks like the result of a newer version of rustc removing the quote feature.  Check again with the latest version.  Now with Rocket 0.4! Thanks to @huntwj
