### ISSUE TITLE
Rocket v0.4 Support

### ISSUE THREAD

**Issue by huntwj** [ghotiphud/rust-web-starter#15]
Thanks for an awesome starter project. Can we get it updated to Rocket v0.4? Please see the attached PR for my attempt at getting things jump started.

https://github.com/ghotiphud/rust-web-starter/pull/14

**Comment by ghotiphud** [comment]
Nice PR, thanks.

**Comment by ghost** [comment]
@ghotiphud @huntwj any chance this could be also done to the diesel_blog branch? I'm learning and reading code really helps :#
